### ISSUE TITLE
Some questions about changing the code

### ISSUE THREAD

**Issue by wushuangmsmw** [bsilvereagle/LeapSTL#1]
When I want to make some changes about your code, the leap motion can not work, even I add a space. So can you give me some advise? Thank you so much.

**Comment by bsilvereagle** [comment]
This code is 3 years old and was written against a (now) deprecated version of the Leap drivers. I suspect that is where your problem lies.

**Comment by wushuangmsmw** [comment]
Thank you for your advice first. I am a graduate researching on bimanual coordination through leap
 motion. I want to realize the zoom function by using leap motion to verify Fitts' Law. Your code contains the zoom function, so I want to make some changes on your code to act as my experimental platform. Is it convenient for you to update the code or can you tell me somewhere else to find similar code? I sincerely thank you for your reply again.

**Comment by bsilvereagle** [comment]
I have lost my Leap Motion, and have written anything since the 2.0 SDK came about. If you're using the SDK, there are plenty of examples on using the Leap to "zoom" in a 3D space in a variety of programming languages. I suggest you check that out.
